hugo-client/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Login;
use app\models\Order;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\mongodb\Query;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [

                'class' => 'yii\authclient\AuthAction',

                // 'successCallback' => [$this, 'successCallback'],

                // 'successUrl' => $this->successUrl,
            ],
        ];
    }


    public function actionIndex()
    {
        if (!AuthController::auth()) {
            $model = new Login;
            $msg = null;
            
            if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            
            if ($model->load(Yii::$app->request->post())) {
                if ($model->validate()) {
                    if (AuthController::login($model->username, $model->password)) {
                        $this->layout = 'main';
                        return $this->render("welcome");
                    } else {
                        $msg = "Credenciales incorrectas";
                        $model->username = null;
                        $model->password = null;
                    }
                } else {
                    $model->getErrors();
                }
            }
            $this->layout = 'login';
            return $this->render("auth", ['model' => $model, 'msg' => $msg]);
        } else {
            return $this->render("welcome");
        }
    }


    public function actionDestroy()
    {
        AuthController::reset();
        return $this->actionIndex();
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogin()
    {
        return $this->actionIndex();
    }

    /**
     * Displays orders page.
     *
     * @return string
     */
    public function actionOrders()
    {
        if (!AuthController::auth()) {
            return $this->actionIndex();
        } else {
            $model = new Order;
            $msg = null;
            
            if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            
            if ($model->load(Yii::$app->request->post())) {
                if ($model->validate()) {
                    OrderController::store($model);
                    $msg = "Ordern agregada correctamente";
                    $model->title = null;
                    $model->color = null;
                } else {
                    $model->getErrors();
                }
            }
            $this->layout = 'main';
            return $this->render("orders", [
                'orders' => OrderController::index(),
                'model' => $model,
                'msg' => $msg
            ]);
        }
    }

    public function actionOrderlist()
    {
        if (!AuthController::auth()) {
            return $this->actionIndex();
        } else {
            $this->layout = 'main';
            return $this->render("orderlist", [
                'orders' => OrderController::index(),
            ]);
        }
    }

    public function actionOrderall()
    {
        if (!AuthController::auth()) {
            return $this->actionIndex();
        } else {
            $this->layout = 'main';
            return $this->render("orderall", [
                'orders' => OrderController::all(),
            ]);
        }
    }

    public function actionComando()
    {
        CommandController::command();
        return $this->render("command");
    }

    public function actionWelcome()
    {
        return $this->render("welcome");
    }

    public function actionCompleteorder()
    {
        OrderController::actionCompleteOrder($_GET);
    }

    public function actionSaluda()
    {
        OrderController::actionCompleteOrder();

        var_dump("hola mundo");
        die();

        // $query = new Query();
        // // compose the query
        // $query->select(['id', 'username'])
        //     ->from('users')
        //     ->limit(100);
        // // execute the query
        // $rows = $query->all();

        return $this->render("saluda");
    }
}

hugo-client/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="icon" type="image/png" href="img/favicon.png" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700&display=swap" rel="stylesheet">

</head>
<body style="background:#38215c">
<?php $this->beginBody() ?>

<div class="login">
    <div class="container">
        <?= $content ?>
    </div>
</div>

<div style="position: absolute;width: 100%;bottom: 0;">
    <footer class="footer">
        <img class="circle-shape" src="img/circle-shape.png" alt="">
        <img class="orange-shape" src="img/orange-shape.png" alt="">
        <div class="container">
            <p class="make-with-love">Hecho con ❤️ por  <a href="https://www.linkedin.com/in/carlos-monge-a8a45436/" target="_blank"><strong> Carlos Monge</strong></a></p>
        </div>
    </footer>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

hugo-client/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="icon" type="image/png" href="img/favicon.png" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700&display=swap" rel="stylesheet">

</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/logo-white.png" class="img-responsive"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Crear una ordene', 'url' => ['/site/orders']],
            ['label' => 'Ordenes', 'url' => ['/site/orderlist']],
            ['label' => 'Todas las ordenes', 'url' => ['/site/orderall']],
            ['label' => 'Comando', 'url' => ['/site/comando']],
            ['label' => 'Salir', 'url' => ['/site/destroy']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <img class="circle-shape" src="img/circle-shape.png" alt="">
    <img class="orange-shape" src="img/orange-shape.png" alt="">
    <div class="container">
        <p class="make-with-love">Hecho con ❤️ por  <a href="https://www.linkedin.com/in/carlos-monge-a8a45436/" target="_blank"><strong> Carlos Monge</strong></a></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>